language: objective-c
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool
    - bundle install
install:
script:
    - pod spec lint 
    - xctool -project MoveDemo/MoveDemo.xcodeproj -scheme MoveDemo -sdk iphonesimulator ARCHS=i386 ONLY_ACTIVE_ARCH=NO build 
